[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs-cli run --chip STM32F401CCUx"

[build]
target = "thumbv7em-none-eabihf"
# rustflags = ["-C", "link-arg=-Tlink.x"]

[env]
DEFMT_LOG = "trace"